blog:
  url: https://yeonyeon.tistory.com
  contents-class-name: post-item
  title-class-name: title
  summary-class-name: excerpt
  date-class-name: date

github:
  access-token: ${ACCESS_TOKEN}
  repo-name: yeon-06/yeon-06
